"""Web Dashboard - Flask web server for the HostBot platform.

Runs on the VPS alongside the Telegram bot (both share MongoDB + Docker).
Users log in with a one-time code generated by the bot (`/web_login`).

Run:
    python web_dashboard.py         # serves http://0.0.0.0:9090 (DASHBOARD_PORT)
"""

import os
import shutil
from datetime import datetime, timedelta
from pathlib import Path

from flask import Flask, jsonify, request, send_from_directory, Response
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer

import database
from config import (
    ENV_ENCRYPTION_KEY, RUNTIME_DIR, WEB_URL, ADMIN_OTP, OWNER_ID, ADMIN_IDS, logger,
)
from docker_manager import docker_exists, docker_logs
from env_manager import get_env_keys, decrypt_env_vars
from security import encrypt_value
from r2_storage import r2_delete, r2_download

WEB_DIR = Path(__file__).parent / "web"

# ---------------------------------------------------------------- auth

# Signed token secret derived from the existing encryption key (never hard-coded).
_TTL = 60 * 60 * 24 * 7  # sessions last 7 days
_serializer = URLSafeTimedSerializer(ENV_ENCRYPTION_KEY or "hostbot-dashboard-secret")


def _make_token(user_id: int) -> str:
    return _serializer.dumps({"uid": user_id})


def _read_token() -> dict | None:
    header = request.headers.get("Authorization", "")
    if not header.startswith("Bearer "):
        return None
    token = header[7:].strip()
    try:
        data = _serializer.loads(token, max_age=_TTL)
        return data if isinstance(data, dict) else None
    except (BadSignature, SignatureExpired):
        return None


app = Flask(__name__)
app.config["JSON_SORT_KEYS"] = False


def _require_user() -> dict:
    data = _read_token()
    if not data:
        raise PermissionError("Not authenticated")
    return data


def _is_admin_uid(uid: int) -> bool:
    if uid == OWNER_ID:
        return True
    if uid in ADMIN_IDS:
        return True
    try:
        if uid in database.db_load_admins():
            return True
    except Exception:
        pass
    return False


def _make_admin_token(user_id: int) -> str:
    return _serializer.dumps({"uid": user_id, "admin": True})


def _require_admin() -> dict:
    data = _read_token()
    if not data or not data.get("admin"):
        raise PermissionError("Not authenticated")
    if not _is_admin_uid(data["uid"]):
        raise PermissionError("Forbidden")
    return data


# ---------------------------------------------------------------- static

@app.route("/")
def index():
    return send_from_directory(WEB_DIR, "index.html")


@app.route("/dashboard")
def dashboard():
    return send_from_directory(WEB_DIR, "dashboard.html")


@app.route("/<path:path>")
def static_files(path):
    return send_from_directory(WEB_DIR, path)


# ---------------------------------------------------------------- api

@app.route("/api/status")
def api_status():
    return jsonify({"status": "ok", "web_url": WEB_URL})


@app.post("/api/login")
def api_login():
    code = (request.get_json(silent=True) or {}).get("code", "").strip()
    if not code:
        return jsonify({"error": "Code is required"}), 400

    database.db_delete_login_code_expired()
    # Login codes are indexed by user_id; find any matching unexpired code.
    found = None
    for row in database.login_col.find({"code": code}):
        try:
            expires = datetime.fromisoformat(row["expires_at"])
        except (ValueError, KeyError):
            continue
        if expires > datetime.utcnow():
            found = row
            break

    if not found:
        return jsonify({"error": "Invalid or expired code"}), 401

    user_id = found["user_id"]
    database.db_delete_login_code(user_id)
    return jsonify({"token": _make_token(user_id), "user_id": user_id})


@app.get("/api/me")
def api_me():
    try:
        data = _require_user()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    uid = data["uid"]
    profile = database.db_get_profile(uid) or {}
    return jsonify(
        {
            "user_id": uid,
            "first_name": profile.get("first_name"),
            "username": profile.get("username"),
            "bio": profile.get("bio"),
            "has_photo": bool(profile.get("photo_key")),
        }
    )


@app.get("/api/me/photo")
def api_me_photo():
    try:
        data = _require_user()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    profile = database.db_get_profile(data["uid"]) or {}
    photo_key = profile.get("photo_key")
    if not photo_key:
        return jsonify({"error": "No photo"}), 404
    try:
        body = r2_download(photo_key)
    except Exception:
        return jsonify({"error": "Photo unavailable"}), 404
    return Response(body, mimetype="image/jpeg")


def _owned_bot(bot_id: int, user_id: int) -> dict | None:
    b = database.db_get_bot(bot_id, user_id)
    if b is None:
        # allow admins to manage any bot
        b = database.db_get_bot_any(bot_id)
        if b is None or user_id not in database.db_load_admins():
            return None
    return b


def _bot_payload(b: dict) -> dict:
    return {
        "id": b["id"],
        "filename": b.get("filename"),
        "file_type": b.get("file_type"),
        "status": b.get("status"),
        "approval": b.get("approval"),
        "env_file_found": b.get("env_file_found"),
        "env_keys": get_env_keys(b["id"]),
        "created_at": b.get("created_at"),
    }


@app.get("/api/bots")
def api_bots():
    try:
        data = _require_user()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    rows = database.db_get_user_bots(data["uid"])
    return jsonify({"bots": [_bot_payload(r) for r in rows]})


@app.get("/api/bots/<int:bot_id>")
def api_bot_detail(bot_id: int):
    try:
        data = _require_user()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    b = _owned_bot(bot_id, data["uid"])
    if not b:
        return jsonify({"error": "Bot not found"}), 404
    return jsonify({"bot": _bot_payload(b)})


@app.post("/api/bots/<int:bot_id>/start")
def api_start(bot_id: int):
    try:
        data = _require_user()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    b = _owned_bot(bot_id, data["uid"])
    if not b:
        return jsonify({"error": "Bot not found"}), 404

    import bot as hostbot
    err = hostbot.start_bot_docker(bot_id)
    if err:
        return jsonify({"error": err}), 400
    fresh = hostbot.db_get_bot_any(bot_id) or b
    return jsonify({"bot": _bot_payload(fresh)})


@app.post("/api/bots/<int:bot_id>/stop")
def api_stop(bot_id: int):
    try:
        data = _require_user()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    b = _owned_bot(bot_id, data["uid"])
    if not b:
        return jsonify({"error": "Bot not found"}), 404

    import bot as hostbot
    hostbot.stop_bot_docker(bot_id)
    fresh = hostbot.db_get_bot_any(bot_id) or b
    return jsonify({"bot": _bot_payload(fresh)})


@app.post("/api/bots/<int:bot_id>/restart")
def api_restart(bot_id: int):
    try:
        data = _require_user()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    b = _owned_bot(bot_id, data["uid"])
    if not b:
        return jsonify({"error": "Bot not found"}), 404

    import bot as hostbot
    hostbot.stop_bot_docker(bot_id)
    err = hostbot.start_bot_docker(bot_id)
    if err:
        return jsonify({"error": err}), 400
    fresh = hostbot.db_get_bot_any(bot_id) or b
    return jsonify({"bot": _bot_payload(fresh)})


@app.get("/api/bots/<int:bot_id>/logs")
def api_logs(bot_id: int):
    try:
        data = _require_user()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    b = _owned_bot(bot_id, data["uid"])
    if not b:
        return jsonify({"error": "Bot not found"}), 404

    cn = b.get("container_name")
    if not cn or not docker_exists(cn):
        return jsonify({"logs": "", "running": False})
    logs = docker_logs(cn, tail=200)
    return jsonify({"logs": logs, "running": True})


@app.get("/api/bots/<int:bot_id>/env")
def api_get_env(bot_id: int):
    try:
        data = _require_user()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    b = _owned_bot(bot_id, data["uid"])
    if not b:
        return jsonify({"error": "Bot not found"}), 404
    env_vars = decrypt_env_vars(bot_id)
    # Return the key and its actual value so the dashboard can show/edit/delete them.
    return jsonify({"env": [{"key": k, "value": env_vars[k]} for k in sorted(env_vars.keys())]})


@app.post("/api/bots/<int:bot_id>/env")
def api_set_env(bot_id: int):
    try:
        data = _require_user()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    b = _owned_bot(bot_id, data["uid"])
    if not b:
        return jsonify({"error": "Bot not found"}), 404

    payload = request.get_json(silent=True) or {}
    key = (payload.get("key") or "").strip()
    value = payload.get("value", "")
    if not key:
        return jsonify({"error": "Key is required"}), 400

    database.db_save_env(bot_id, key, encrypt_value(str(value)))
    env_vars = decrypt_env_vars(bot_id)
    return jsonify({"env": [{"key": k, "value": env_vars[k]} for k in sorted(env_vars.keys())]})


@app.delete("/api/bots/<int:bot_id>/env/<path:key>")
def api_delete_env(bot_id: int, key: str):
    try:
        data = _require_user()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    b = _owned_bot(bot_id, data["uid"])
    if not b:
        return jsonify({"error": "Bot not found"}), 404
    database.db_delete_env(bot_id, key)
    env_vars = decrypt_env_vars(bot_id)
    return jsonify({"env": [{"key": k, "value": env_vars[k]} for k in sorted(env_vars.keys())]})


@app.delete("/api/bots/<int:bot_id>")
def api_delete_bot(bot_id: int):
    try:
        data = _require_user()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    b = _owned_bot(bot_id, data["uid"])
    if not b:
        return jsonify({"error": "Bot not found"}), 404

    if b["status"] == "running":
        import bot as hostbot
        hostbot.stop_bot_docker(bot_id)

    try:
        if b.get("r2_key"):
            r2_delete(b["r2_key"])
    except Exception as e:
        logger.error("R2 delete bot=%d: %s", bot_id, e)

    database.db_delete_all_envs(bot_id)

    d = RUNTIME_DIR / str(bot_id)
    if d.exists():
        shutil.rmtree(d, ignore_errors=True)

    database.db_delete_bot(bot_id)
    return jsonify({"deleted": True})


# ---------------------------------------------------------------- admin

MAINTENANCE_NOTICE = (
    "🔧 <b>The bot is currently under maintenance.</b>\n\n"
    "Please try again later. Thank you for your patience!"
)


@app.post("/api/admin/login")
def api_admin_login():
    body = request.get_json(silent=True) or {}
    try:
        uid = int(body.get("uid", ""))
    except (TypeError, ValueError):
        return jsonify({"error": "Invalid Telegram UID"}), 400
    otp = (body.get("otp") or "").strip()
    if not _is_admin_uid(uid):
        return jsonify({"error": "This UID is not an admin"}), 403
    if not ADMIN_OTP:
        return jsonify({"error": "Admin OTP is not configured on the server"}), 500
    if otp != ADMIN_OTP:
        return jsonify({"error": "Invalid OTP"}), 401
    return jsonify({"token": _make_admin_token(uid), "admin": True})


@app.get("/api/admin/me")
def api_admin_me():
    try:
        data = _require_admin()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    return jsonify({"admin": True, "user_id": data["uid"]})


@app.get("/api/admin/maintenance")
def api_admin_maintenance_get():
    try:
        _require_admin()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    on = database.db_is_maintenance()
    notice = database.db_get_setting("maintenance_notice", MAINTENANCE_NOTICE)
    return jsonify({"maintenance": on, "notice": notice})


@app.post("/api/admin/maintenance")
def api_admin_maintenance_set():
    try:
        _require_admin()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    body = request.get_json(silent=True) or {}
    on = bool(body.get("maintenance"))
    database.db_set_setting("maintenance", on)
    notice = (body.get("notice") or "").strip() or MAINTENANCE_NOTICE
    database.db_set_setting("maintenance_notice", notice)
    logger.warning("Maintenance set to %s by admin %d", on, _read_token()["uid"])
    if on:
        database.db_save_outbox("broadcast", notice)
    return jsonify({"maintenance": on, "notice": notice})


@app.post("/api/admin/broadcast")
def api_admin_broadcast():
    try:
        _require_admin()
    except PermissionError:
        return jsonify({"error": "Not authenticated"}), 401
    body = request.get_json(silent=True) or {}
    text = (body.get("text") or "").strip()
    if not text:
        return jsonify({"error": "Message is required"}), 400
    database.db_save_outbox("broadcast", text)
    return jsonify({"queued": True})


# ---------------------------------------------------------------- run

def main() -> None:
    database.init_db()
    port = int(os.environ.get("DASHBOARD_PORT", "8000"))
    host = os.environ.get("DASHBOARD_HOST", "0.0.0.0")
    logger.info("Dashboard running on http://%s:%s", host, port)
    app.run(host=host, port=port, threaded=True)


if __name__ == "__main__":
    main()
